# Uncomment this line to define a global platform for your project

platform :ios, '9.0'
workspace ‘iCycle’
use_frameworks!

target 'iCycle' do

  pod 'Alamofire', '~> 3.0'
  pod 'MySqlSwiftNative', '~> 1.0.6'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  #pod 'CommonCrypto', '~> 1.1'

end